server:
  port: 8765 #服务端口

eureka:
  client:
    serviceUrl: #指定服务注册中心地址，类型为 HashMap，并设置有一组默认值，默认的Key为 defaultZone；默认的Value为 http://localhost:8761/eureka ，如果服务注册中心为高可用集群时，多个注册中心地址以逗号分隔
      defaultZone: http://localhost:8761/eureka/  #Eureka客户端和服务端进行交互的地址，服务注册中心的地址

spring:
  application:
    name: service-feign-hystrix  #服务名
    
feign:
  hystrix:
    enabled: true  #Feign中集成hystrix，只需在配置文件中开启即可
# Feign超时设置
# Feign的调用分两层，即Ribbon的调用和Hystrix的调用，高版本的Hystrix默认是关闭的
ribbon:
  ReadTimeout: 120000
  ConnectionTimeout: 30000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
