server:
  port: 8989
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      #      routes:
      #      - id: ribbon_route
      #        uri: http://localhost:8700/
      #        predicates:
      #        - Path=/ribbon/**
      #        filters:
      #        - RewritePath=/ribbon/(?<segment>.*), /$\{segment}
      #      - id: feign_route
      #        uri: http://localhost:8701/
      #        predicates:
      #        - Path=/feign/**
      #        filters:
      #        - RewritePath=/feign/(?<segment>.*), /$\{segment}
      # 会自动为每个服务创建一个默认的路由规则
      discovery:
        locator:
          enabled: true # 开启基于服务发现的路由规则
          lower-case-service-id: true # 开启用小写的serviceId进行基于服务路由的转发
logging:
  level:
    org.springframework.cloud.gateway: debug
