server:
  port: 1111

spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://peer2:1112/eureka/
